GET http://localhost:5000/queue

###
GET http://localhost:5000/queue/1

###
POST http://localhost:5000/queue
Content-Type: application/json

{
    "name": "Nama 2",
    "phone_number": "0000000000"
}


###
PATCH  http://localhost:5000/queue/2
Content-Type: application/json

{
    "name": "Nama 2",
    "phone_number": 872456789
}

###
DELETE http://localhost:5000/queue/3